apiVersion: apps/v1
kind: Deployment
metadata:
  name: agrold-vue-frontend
  labels:
    app:  agrold-vue-frontend
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  agrold-vue-frontend
  template:
    metadata:
      labels:
        app:  agrold-vue-frontend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name:  agrold-vue-frontend
          image: ghcr.io/southgreenplatform/agrold-new-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "125m"
              memory: "500Mi"
            limits:
              cpu: "250m"
              memory: "1Gi"

---
apiVersion: v1
kind: Service
metadata:
  name:  agrold-vue-frontend-svc
  labels:
    app: agrold-vue-frontend
spec:
  ports:
    # - targetPort: 3000
    - name: http
      protocol: TCP
      port: 3000
  selector:
    app: agrold-vue-frontend


---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: letsencrypt
    cert-manager.io/issuer-kind: Issuer
    haproxy.router.openshift.io/timeout: 5m
  labels:
    app.kubernetes.io/instance: agrold-vue-frontend
    # app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: agrold-vue-frontend
    app.kubernetes.io/version: 1.1.2
    # helm.sh/chart: relfinder-reformed-2.0.0
  name: agrold-vue-frontend-ingress
  namespace: agrold
spec:
  rules:
    - host: vue-dev.agrold.org
      http:
        paths:
          - backend:
              service:
                name: agrold-vue-frontend-svc
                port:
                  name: http
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - vue-dev.agrold.org
      secretName: vue-dev.agrold.org-tls

---

apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: agrold
  annotations:
    "argocd.argoproj.io/sync-options": "Replace=true"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiQmlsbEdhdGVzOTgiLCJwYXNzd29yZCI6ImdocF9xdVVINE1lWEZqTFY4amZiZ0doV2puaHhqT01vZjkwd1ZVdEkiLCJlbWFpbCI6ImJpbGxoYXBwaUBnbWFpbC5jb20iLCJhdXRoIjoiUW1sc2JFZGhkR1Z6T1RnNloyaHdYM0YxVlVnMFRXVllSbXBNVmpocVptSm5SMmhYYW01b2VHcFBUVzltT1RCM1ZsVjBTUT09In19fQ==